name: vienna_airport_taxi
description: "A taxi booking app for Vienna Airport."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # State management
  provider: ^6.1.1
  # Network and API
  http: ^1.1.0
  dio: ^5.3.2
  # Local storage
  shared_preferences: ^2.2.1
  # UI components
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.11
  google_fonts: ^6.1.0
  # For SVGator animations
  webview_flutter: ^4.4.2
  # Utilities
  intl: ^0.19.0
  geolocator: ^10.1.0
  # Authentication
  # firebase_core: ^2.15.1
  # firebase_auth: ^4.9.0
  # Form validation
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.11.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/hero_section/
    - assets/images/header/
    - assets/images/splash/
    - assets/images/booking_section/
    - assets/icons/inputs/
    - assets/lang/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon_1024.png"
